name: TradeShop-LOG
version: ${project.version}
main: org.shanerx.tradeshoparm.TradeShopLOG
api-version: 1.14
load: POSTWORLD
depend: [TradeShop]

authors: [Lori00, KillerOfPie]
description: ${project.description}
website: ${project.url}
